name: "Prepare Python"
description: "Python ランタイムと依存パッケージをインストールし、Python バージョンを出力する"

inputs:
  dependency-group:
    description: "uv の依存パッケージインストール時に指定するグループ"
    required: false

runs:
  using: "composite"
  steps:
    - name: <Setup> Get cache-suffix
      if: ${{ runner.os == 'Linux' }}
      id: cache-suffix
      run: |
        $(gcc --print-file-name=libc.so.6) | \
          awk 'NR==1 {print "CACHE_SUFFIX=glibc-" $NF}' >> "$GITHUB_OUTPUT"
      shell: bash

    - name: <Setup> Install uv
      uses: astral-sh/setup-uv@v7
      with:
        enable-cache: true
        cache-suffix: ${{ steps.cache-suffix.outputs.CACHE_SUFFIX }}

    - name: <Setup> Install Python dependencies
      run: |
        if [[ -n "${{ inputs.dependency-group }}" ]]; then
          uv sync --group ${{ inputs.dependency-group }}
        else
          uv sync
        fi
      shell: bash
