name: Test Release

on:
  push:

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macOS-latest]

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Create large files
        run: |
          python -c "
          import os

          for i in range(5):
              with open(f'large_file_{i}.bin', 'wb') as f:
                  f.write(os.urandom(1024 * 1024 * 1024))  # 1 GB
          "

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: |-
            large_file_0.bin,large_file_1.bin,large_file_2.bin,large_file_3.bin,large_file_4.bin
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: test
          allowUpdates: true
